### ISSUE TITLE
Unable to change Stream key!

### ISSUE THREAD

**Issue by mattmcd93** [bitfocus/companion-module-bmd-webpresenter#12]
Hey I am unable to use the "WebPresenter: Stream Settings" button to changer my stream key.
I would like the ability to switch from my test stream key on YouTube with my regular stream key via companion.

please let me know if this is possible with this plug in.
I am using the web presenter 4k

**Comment by daniep01** [comment]
Yes, this is definitely possible. Did you also put in the platform 'YouTube' and  server 'Primary'.

**Comment by mattmcd93** [comment]
Hey! think that fixed it. just had to write primary.
and I had issues having two commands on the same button. once I put them on different buttons, one for stream one for test... it seems to be working! thanks!
