### ISSUE TITLE
WebPresenter 4k Stream Settings Not Updating

### ISSUE THREAD

**Issue by Kthomas3** [bitfocus/companion-module-bmd-webpresenter#13]
Successfully connected WebPresenter and stream start/stop is working however updating stream settings is not.  

Using WebPresenter: Stream Settings will trigger a change in the Video Mode, however, Platform, Server, Key, and Quality are not changing or updating.

**Comment by daniep01** [comment]
The settings you enter for platform and server must match exactly those used by the Blackmagic desktop app otherwise they are not accepted.

**Comment by Kthomas3** [comment]
That was it, I was entering the server url when something like Default or Auto was needed to match the app.  Thank you!

**Comment by davidjoshuaford** [comment]
However, to add to this thread, while I can set the Server field to "Primary" instead of an actual server url for YouTube RTMP, it doesn't appear to work for the Custom URL H.264 or Custom URL H.265 options. 

Anyone found that to be the case also?

**Comment by daniep01** [comment]
@davidjoshuaford The H265 and SRT options were added in firmware released on 15/Sep/23 and it looks like I will need to update the module to include these.

**Comment by davidjoshuaford** [comment]
That’d be great, thanks 

for my knowledge, can all these fields accept custom variables? 

Use case is I’m using a Shopify plugin platform called Firework and it needs a fresh stream key for every livestream, so I’m trying to find a workflow that can automatically update the custom URLs via a custom variable.

**Comment by daniep01** [comment]
> However, to add to this thread, while I can set the Server field to "Primary" instead of an actual server url for YouTube RTMP, it doesn't appear to work for the Custom URL H.264 or Custom URL H.265 options.
> 
> Anyone found that to be the case also?

@davidjoshuaford 
I have figured out why this isn't working, I need to add an extra command for setting the custom URL

**Comment by davidjoshuaford** [comment]
Great thanks - I'll test it in the next beta push. Thanks!
