### ISSUE TITLE
Request: Individual Actions for Stream Settings

### ISSUE THREAD

**Issue by nickvanhouten** [bitfocus/companion-module-bmd-webpresenter#16]
Hi There,

Could these stream settings actions be broken out into separate commands within Companion? For instance, I would like to re-assert the streaming quality but not affect the other settings.

Thanks.
![Screen Shot 2023-11-05 at 11 48 38 AM](https://github.com/bitfocus/companion-module-bmd-webpresenter/assets/65696939/e61da4ce-3068-481d-ad72-7dae1cc16551)

**Comment by daniep01** [comment]
Yes, this is possible, I will add more actions.

**Comment by daniep01** [comment]
Here is a test release with the new actions if you would like to test it let me know how you get on

[pkg.tgz](https://github.com/bitfocus/companion-module-bmd-webpresenter/files/13277914/pkg.tgz)
