### ISSUE TITLE
[BUG]  WebPresenter: Stream Settings BROKEN...

### ISSUE THREAD

**Issue by kooscode** [bitfocus/companion-module-bmd-webpresenter#17]
WebPresenter Sofware Version: 3.4

When using the WebPresenter: Stream Settings to set specific stream settings does nothing..

NONE of the stream settings seems to take effect.. the unit keeps current settings after action.. 

Also, the "custom h.265"  does not support SRT..   for example there is no "key", but could have optional "passphrase"

**Comment by daniep01** [comment]
Firmware version 3.4 is not currently supported. If you downgrade to 3.3 it will work.

**Comment by kooscode** [comment]
Did the protocol change between 3.3 and 3.4?

**Comment by LSCkonamedia** [comment]
I have the same problem.... Downgrading to 3.3 did not fix the issue :( Any thing i might be missing?

**Comment by daniep01** [comment]
Could you show the action you are sending to the web presenter that isn't working?

**Comment by LSCkonamedia** [comment]
[image: Screenshot 2024-02-25 065102.png]

**Comment by daniep01** [comment]
Hi, I don't think images can be sent to GitHub by email, I can only see text.

**Comment by LSCkonamedia** [comment]
![Screenshot 2024-02-25 065102](https://github.com/bitfocus/companion-module-bmd-webpresenter/assets/161234739/890a3fe0-5f02-4465-b3d3-25775efa8087)

**Comment by daniep01** [comment]
Try typing "Default" in the Server field.

**Comment by daniep01** [comment]
I just tested it and it works for me. Did you put a capital 'D' at the start of 'Default' in the server field?

https://github.com/bitfocus/companion-module-bmd-webpresenter/assets/17852298/a8d48b68-7492-4f9e-b9d0-1be1f9936173

**Comment by daniep01** [comment]
> Also, the "custom h.265" does not support SRT.. for example there is no "key", but could have optional "passphrase"

In the WebPresenter app it is the same, the passphrase is box is disabled for Custom H265

<img width="329" alt="image" src="https://github.com/bitfocus/companion-module-bmd-webpresenter/assets/17852298/61216109-71bc-4018-9891-2fb1f5badc2c">
