### ISSUE TITLE
WEbpresenter 4K does not reconnect in Companion

### ISSUE THREAD

**Issue by pgordemer** [bitfocus/companion-module-bmd-webpresenter#19]
If I restart webpresenter, the companion module does not reconnect. I have to disable and reenable to get it to connect.

**Comment by DAllen1750** [comment]
I have the HD version of the web presenter and have the same issue. On reboot, the device does not connect. The connection times out based on the log. I have to toggle the device off and back on for it to connect. 
[module-log-2_11_2024-9_18_57 AM.csv](https://github.com/bitfocus/companion-module-bmd-webpresenter/files/14232691/module-log-2_11_2024-9_18_57.AM.csv)

**Comment by huntrohrer** [comment]
I have the HD version as well and experience this issue. I attempted to set up a trigger as a work around, but I have not had success with that yet.

For our system we have 2 BlackMagic ATEM switchers when I power those down Companion says "Connecting..." but when the WebPresenter is powered down it says there is an Error.

**Comment by huntrohrer** [comment]
> I have the HD version as well and experience this issue. I attempted to set up a trigger as a work around, but I have not had success with that yet.
> 
> For our system we have 2 BlackMagic ATEM switchers when I power those down Companion says "Connecting..." but when the WebPresenter is powered down it says there is an Error.

My current work around is I added two steps to a button the first disables the internal connection to the WebPresenter then 10 secs. later it enables again. That has solved the issue for the time being.

**Comment by daniep01** [comment]
I'll look at this next time I get hold of a device for testing

**Comment by daniep01** [comment]
fixed in release 2.1.1
